Add variables feature

diff --git a/parapane b/parapane
--- a/parapane
+++ b/parapane
@@ -10,7 +10,11 @@ function command_list() {
       [[ -z $section ]] || parse_section $section || exit 1
       section=$line
     else
-      eval param_${line}
+      if [[ $section == '[definitions]' ]]; then
+        eval $line
+      else
+        eval param_${line}
+      fi
     fi
   done
 }
@@ -19,13 +23,15 @@ function command_list() {
 function parse_section() {
   local section=$1
   if [[ $section = '[command]' ]]; then
-    [[ -z $param_exec ]] && echo 'not found a key: exec' >&2 && exit 1
+    [[ -z $param_exec ]] && echo 'not found a key: "exec"' >&2 && exit 1
     echo $param_exec
   elif [[ $section = '[sleep]' ]]; then
     [[ -z $param_sec ]] && echo 'not found a key: "sec"' >&2 && exit 1
     echo "sleep ${param_sec}"
   elif [[ $section = '[new-window]' ]]; then
     echo 'new-window'
+  elif [[ $section = '[definitions]' ]]; then
+    :
   else
     echo "unknown section was found: ${section}" >&2
     exit 1
@@ -35,13 +41,13 @@ function parse_section() {
 
 function split_and_run() {
   local run_cmd
-  local sleep_cmds=''
+  local common_cmds=''
   local panes_cnt=0
   local windows_cnt=0
   cat - | while read -r cmd; do
     if [[ $cmd == sleep* ]]; then
-      sleep_cmds="${sleep_cmds}; ${cmd}"
-      sleep_cmds="${sleep_cmds#; }"
+      common_cmds="${common_cmds}; ${cmd}"
+      common_cmds="${common_cmds#; }"
       continue
     fi
     if [[ $cmd == new-window ]]; then
@@ -56,7 +62,11 @@ function split_and_run() {
       tmux split-window
       tmux select-layout tiled
     fi
-    run_cmd="${sleep_cmds}; ${cmd}"
+    run_cmd="${cmd}"
+    if [[ -n "${common_cmds}" ]]; then
+      run_cmd="${common_cmds}; ${run_cmd}"
+    fi
+    echo $run_cmd
     tmux send-keys "${run_cmd#; }" C-m
 
     panes_cnt=$(($panes_cnt + 1))
@@ -69,10 +79,11 @@ function split_and_run() {
 
 
 function run_commands() {
-  commands=$(cat - \
-    | sed -E 's/;.*$//; s/(^ +| +$)//; /^$/d' | sed -E '$s/$/\n[EOF]/' \
-    | command_list) || exit 0
-  echo "$commands" | split_and_run
+  cat - \
+    | sed -E 's/;.*$//; s/(^ +| +$)//; /^$/d' \
+    | sed -E '$s/$/\n[EOF]/' \
+    | command_list \
+    | split_and_run
 }
 
 
